### PR TITLE
Docs example fix: all-users resolver example and some typos

### PR DESCRIPTION
**Pull request by yannvanhalewyn**
This resolver would either result in a 'not-found' or 'invalid resolve response' exception. I caught this when going through the docs and not getting this to work.
I also threw in some free typos I noticed 😉.

I'm working through the guide and I am absolutely loving Pathom so far. Amazing work and thank you!

### CODE REVIEW

**Comment by yannvanhalewyn** [comment]
I can't seem to rebuild the docs, I'm getting:

> error: Specified UI bundle does not exist: /Users/wilker.lucio/Development/third-part/docs-ui/build/ui-bundle.zip

I think it might be easier if someone else takes care of this.

**Comment by wilkerlucio** [comment]
Hello, sorry about the build problem, did you tried using `antora docs-dev.yml`? That setup should use the local sources and also use a remote UI bundle. I also add these same instructions to the README for further users: https://github.com/wilkerlucio/pathom#building-the-docs.

Can you please check if those instructions work for you? Thanks.

**Comment by wilkerlucio** [comment]
But anyway, for the release build I can do here, this is just to check if you can test it locally.

**Comment by wilkerlucio** [comment]
Thanks for the fixes.

**Comment by yannvanhalewyn** [comment]
@wilkerlucio Thanks for the quick merge! I can confirm that `antora docs-dev` worked on my machine. 👍

**Comment by yannvanhalewyn** [comment]
For completeness it dit output this warning:

> asciidoctor: WARNING: skipping reference to missing attribute: thing-by-id 

And I also see some 127.0.0.1:8080 anchor tags in the diff, which might be unsuitable for creating pull requests if checked in accidentally (FYI)

**Pull request merged**
