### PR TITLE
[WIP] General proofreading and improving the readability of docs

### PR DESCRIPTION
**Pull request by abhi18av**
This is basically a doc PR for the irregularities and possible improvements I noticed while going through the docs.

As of now, it's in `WIP` so that I can a have your feedback and then I'll mark it as `Complete` once I've gone through the entire docs.

### CODE REVIEW

**Comment by abhi18av** [comment]
Oh, I just noticed another doc PR!

For reference, there are a few overlaps with https://github.com/wilkerlucio/pathom/pull/108 , which I'll incorporate  or rebase once that PR is merged.

**Comment by abhi18av** [comment]
Changing the status to `Complete` now, since I've covered the dev guide.

I'll be awaiting your feedback before giving it the finishing touches to finalize/rollback certain things.

**Comment by wilkerlucio** [comment]
Hello man, thanks for taking the time. But there is one thing going, I'm currently changing a lot of the docs, the big index.adoc is getting broken in many files, and there were some changes in the middle. You can find the new stuff at https://github.com/wilkerlucio/pathom/tree/docs-v2

Sorry about the confusion, but if you can make the changes there would be great. I plan to merge that branch quite soon, so it will be less confusing for people to edit over.

**Comment by abhi18av** [comment]
😅 hehe, bummer!

Well, I sure can go through those but will take a few days to get around this time. Also, for future reference, might be a good idea these transition things on the ReadMe :)

**Comment by wilkerlucio** [comment]
Yeah, sorry, in a few years of project there were very few and narrow contributions so I wasn't with this scale of contribution coming, really sorry about that, I just updated the README so other people get aware of that.

**Comment by abhi18av** [comment]
@wilkerlucio, a lot more coming. Brace yourself 😊

**Comment by abhi18av** [comment]
I'm closing this PR in favor or porting over the corrections to the newer version of the docs.

**Pull request closed without merging**
