### PR TITLE
Fix `transform-remote` setting invalid ::fulcro.network/progress-handler

### PR DESCRIPTION
**Pull request by lucasdesenna**
## Description

I stumbled into this issue while investigating reports of Fulcro Inspect (legacy) not being able to perform queries while connected to the remotes of a Fulcro App in the company I work for.

The failed queries would also produce an `Uncaught TypeError: Cannot read property 'cljs$core$IFn$_invoke$arity$1' of null` exception which was associated with [this line](https://github.com/wilkerlucio/pathom/blob/master/src/com/wsscode/pathom/fulcro/network.cljs#L118) and indicated that the `progress-handler` argument was missing.

After some investigation, I realized that the `::fulcro.network/progress-handler` attribute [is optional](https://github.com/fulcrologic/fulcro/blob/2.8.13/src/main/fulcro/client/network.cljc#L345-L349), and when used on a network that lacks it, the `com.wsscode.pathom.fulcro.network/transform-remote` creates a network with an invalid progress-handler.

## How to reproduce the bug?

1. Create a Fulcro network without declaring a `::fulcro.network/progress-handler`.
2. Transform said network using `com.wsscode.pathom.fulcro.network/transform-remote`.
3. Perform a network operation using the transformed network. This should cause the error described above.

## Changes

This PR modifies the options map of the `transmit` function as to only contain the `::fulcro.network/progress-handler` attribute when the provided `progress-handler` is not `nil`. When the handler is not provided, Fulcro automatically ignores progress events in network operations.

### CODE REVIEW

**Comment by lucasdesenna** [comment]
`Testing com.wsscode.pathom.connect-test` doesn't fail when I run the tests locally. Do you know what might be wrong?

**Comment by wilkerlucio** [comment]
Thanks!

**Comment by wilkerlucio** [comment]
Released on `[com.wsscode/pathom "2.3.0-alpha20"]`

**Comment by lucasdesenna** [comment]
Thank you, man. Keep up the good work.

**Pull request merged**
