### PR TITLE
Fix inline unions on mutation subquery

### PR DESCRIPTION
**Pull request by ArthurJordao**
This PR adds support to inline unions on GraphQL mutation subqueries.

### CODE REVIEW

**Comment by ArthurJordao** [comment]
Hello, @wilkerlucio could you help us here :please:?

**Comment by wilkerlucio** [comment]
Hello, sorry for the delay in response, I'm currently traveling and my open source time has been a bit restricted.

This looks good, can you please update your branch with master? I recently finished the CI test running here on Github, so if you update we get the pipeline to run!

**Comment by ArthurJordao** [comment]
@wilkerlucio no problem, thank you for reviewing my PR. I just updated it with the master branch, it should work now. :)

**Comment by wilkerlucio** [comment]
Hey Artur, I'm trying to understand why the checks are not running, I expected them to do it.

Can you please try editing the file https://github.com/wilkerlucio/pathom/blob/master/.github/workflows/test.yml#L3

**Comment by ArthurJordao** [comment]
It worked now! @wilkerlucio

**Comment by wilkerlucio** [comment]
@ArthurJordao `2.3.0-alpha7` released now.

**Pull request merged**
