### PR TITLE
[Complete] Proof-reading done for the pathom-connect docs

### PR DESCRIPTION
**Pull request by abhi18av**
I've completed the corrections for `pathom-connect` docs.

### CODE REVIEW

**Comment by abhi18av** [comment]
Next, I plan to pick up `core` docs :)

**Comment by wilkerlucio** [comment]
nice!

**Comment by wilkerlucio** [comment]
About core, please ping me before starting on that, I'm doing some significant changes on it, some pages may be better hold

**Comment by abhi18av** [comment]
Okay, thanks for the heads up!

**Pull request merged**
