### PR TITLE
Fix caching issues when using batch resolvers with the parallel-reader

### PR DESCRIPTION
**Pull request by ak-coram**
Hi,

I've reported a related issue on the slack channel recently about a
batch resolver sporadically being called with `nil` input leading to
`not-found` in the results of a query. Sadly I can't reproduce it with
a minimal example, but came up with a fix which at least resolves the
issue for me and doesn't break any tests.

In the current version `parallel-batch` removes already cached items
from the `processing-sequence`. This can lead to the resolver being
called with `nil` when all the items are already in the
cache. Furthermore this leads to no result being returned for these
items.

This PR first groups the items into cached and uncached
categories. The uncached items are processed as before, except when
there are no such items the resolver call is omitted. The cached items
don't require further processing, except their result is returned
after reading it from the cache.

Could you please give me a bit of feedback on this approach? Thanks!

### CODE REVIEW

**Comment by ak-coram** [comment]
I've rebased my changes on top of the latest master.

**Comment by wilkerlucio** [comment]
Hello @ak-coram, sorry for the delay, it has been a busy week, but I have on my list to check this ASAP.

**Comment by ak-coram** [comment]
Hi @wilkerlucio, no worries :)

Let me know if I can help with anything.

**Comment by wilkerlucio** [comment]
Ok, I finally got some looking at it. The tests are still passing, but can you please add a new test case to ensure that the issue you saw didn't get re-introduced later?

**Comment by ak-coram** [comment]
It was a bit tricky to reproduce this issue within a test (since it
only occurs when multiple batches are processed concurrently), but
I've added a test which fails on my machine with the current `master`
branch and works after applying the changes from this branch. With my
setup the issue only occurred in about 50% of the test runs, so I've
resorted to running the test multiple times (with `pmap`) to increase
reliability a bit.

Please let me know if you can reproduce this on your end. Thanks!

**Comment by wilkerlucio** [comment]
Thanks!

**Pull request merged**
